### ISSUE TITLE
tutorial about ssh'ing into managed openshift nodes

### ISSUE THREAD

**Issue by stevemar** [stevemar/stevemar.github.io#20]
the file `inspect-node.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: inspectnode164121
  labels:
    name: inspectnode
  namespace: kube-system
spec:
  tolerations:
    - operator: "Exists"
  hostNetwork: true
  containers:
    - name: inspectnode164121
      image: nkkashyap/inspectndoe:v001 
      volumeMounts:
      - mountPath: /host/root
        name: host-root
      - mountPath: /host/etc
        name: host-etc
      - mountPath: /host/log
        name: host-log
      - mountPath: /host/local
        name: host-local
      - mountPath: /run/systemd
        name: host-systemd

  volumes:
  - name: host-root
    hostPath:
      path: /root/
  - name: host-etc
    hostPath:
      path: /etc
  - name: host-log
    hostPath:
      path: /var/log
  - name: host-local
    hostPath:
      path: /usr/local
  - name: host-systemd
    hostPath:
      path: /run/systemd

  nodeSelector:
    kubernetes.io/hostname: WORKER NODE NAME
```

Then you need to run through these commands:

```bash
kubectl create -f ./inspect-node.yaml
```

then exec into pod

```bash
kubectl exec -it -n kube-system <pod name> /bin/bash
```

Now from inside the POD enable root login

```bash
sed -i 's/PermitRootLogin no/PermitRootLogin yes/g' /host/etc/ssh/sshd_config
```

Restart the ssh daemon on the worker node

```bash
./systemutil  -service sshd.service
```

Now (still from within the container), ssh to worker node

```bash
ssh root@localhost
```
